name: MonoGS
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=11.7
  - plyfile=0.8.1
  - python=3.10.14
  - pip=22.3.1
  - pytorch=1.13.1
  - torchaudio=0.13.1
  - torchvision=0.14.1
  - tqdm
  - pip:
    - submodules/simple-knn
    - submodules/diff-gaussian-rasterization
    - munch
    - ninja
    - opencv-python
    - trimesh
    - evo==1.11.0
    - open3d==0.17.0
    - matplotlib==3.5.3
    - torchmetrics
    - imgviz
    - PyOpenGL
    - glfw
    - PyGLM
    - wandb
    - lpips
    - rich
    - ruff
