inherit_from: "thirdparty/MonoGS/configs/mono/vivid/base_config.yaml"

Dataset:
  modality: 'Thermal_vis'

  dataset_path: "datasets/VIVID/indoor_robust_varying"
  Calibration:
    fx: 437.38861083256637
    fy: 437.29475745770907
    cx: 323.5284494924228
    cy: 256.36315482047905
    k1: 0.0
    k2: 0.0
    k3: 0.0
    k4: 0.0
    width: 640
    height: 512
    depth_scale: 1.0
    distorted: False
    distortion_model: ''
