inherit_from: "configs/mono/vivid/base_config.yaml"

Dataset:
  modality: 'Thermal'

  dataset_path: "datasets/VIVID_256/indoor_robust_varying"
  Calibration:
    fx: 2.186943054162831857e+02
    fy: 2.186473787288545338e+02
    cx: 1.617642247462113971e+02
    cy: 1.281815774102395267e+02
    k1: 0.0
    k2: 0.0
    k3: 0.0
    k4: 0.0
    width: 320
    height: 256
    depth_scale: 1.0
    distorted: False
    distortion_model: ''
