inherit_from: "thirdparty/MonoGS/configs/mono/vivid/base_config.yaml"

Dataset:
  modality: 'RGB'

  dataset_path: "datasets/VIVID/indoor_robust_varying"
  Calibration:
    fx: 531.0787710720505
    fy: 530.9280349280389
    cx: 322.0434384516226
    cy: 239.58555406488455
    k1: 0.0
    k2: 0.0
    k3: 0.0
    k4: 0.0
    width: 640
    height: 480
    depth_scale: 1.0
    distorted: False
    distortion_model: ''
