inherit_from: "nerf_vo/thirdparty/MonoGS/configs/mono/vivid/base_config.yaml"

Dataset:
  modality: 'visual'

  dataset_path: "datasets/VIVID/outdoor_robust_day1"
  Calibration:
    fx: 2.655393855360252360e+02
    fy: 2.831616186282873855e+02
    cx: 1.610217192258112959e+02
    cy: 1.277789621679384169e+02
    k1: 0.0
    k2: 0.0
    k3: 0.0
    k4: 0.0
    width: 320
    height: 256
    depth_scale: 1000.0
    distorted: False
    distortion_model: ''
