inherit_from: "configs/mono/tum/base_config.yaml"

Dataset:
  dataset_path: "datasets/tum/rgbd_dataset_freiburg1_desk/"
  Calibration:
    raw:
      fx: 517.306408
      fy: 516.469215
      cx: 318.643040
      cy: 255.313989
      k1: 0.262383
      k2: -0.953104
      p1: -0.005358
      p2: 0.002628
      k3: 1.163314
      width: 640
      height: 480
      depth_scale: 5000.0
      distorted: True
    opt:
      fx: 258.6532
      fy: 258.2346
      cx: 159.3215
      cy: 127.6570
      k1: 0.0
      k2: 0.0
      p1: 0.0
      p2: 0.0
      k3: 0.0
      width: 320
      height: 240
      depth_scale: 5000.0
      distorted: False



