Results:
  save_results: True
  save_dir: "results"
  save_trj: True
  save_trj_kf_intv: 10
  use_gui: True
  eval_rendering: False
  use_wandb: True

Dataset:
  type: 'rrxio'
  sensor_type: 'monocular'
  modality: 'thermal'
  pcd_downsample: 64
  pcd_downsample_init: 32
  adaptive_pointsize: True
  point_size: 0.01

  dataset_path: "/media/pi/BackupPlus/jhuai/data/rrxio/irs_rtvi_datasets_2021/mocap_easy"
  Calibration:
    raw:
      fx: 404.98
      fy: 405.06
      cx: 319.05
      cy: 251.84
      k1: -0.09202092749042277
      k2: 0.04012198239889151
      k3: -0.03795923559427829
      k4: 0.010728597805678742
      width: 640
      height: 512
      depth_scale: 500.0
      distorted: True
      distortion_model: 'equidistant'
    opt:
      # K optimal obtained by cv2.fisheye.estimateNewCameraMatrixForUndistortRectify() with balance=0.0
      fx: 334.19639643
      fy: 334.26241379
      cx: 318.48142004
      cy: 250.56663663
      k1: 0.0
      k2: 0.0
      k3: 0.0
      k4: 0.0
      width: 640
      height: 512
      depth_scale: 500.0
      distorted: False
      distortion_model: ''

Training:
  init_itr_num: 1050
  init_gaussian_update: 100
  init_gaussian_reset: 500
  init_gaussian_th: 0.005
  init_gaussian_extent: 30
  tracking_itr_num: 100
  mapping_itr_num: 150
  gaussian_update_every: 150
  gaussian_update_offset: 50
  gaussian_th: 0.7
  gaussian_extent: 1.0
  gaussian_reset: 2001
  size_threshold: 20
  kf_interval: 5
  window_size: 8
  pose_window: 3
  edge_threshold: 1.1
  rgb_boundary_threshold: 0.01

  kf_translation: 0.08
  kf_min_translation: 0.05
  kf_overlap: 0.9
  kf_cutoff: 0.3
  prune_mode: 'slam'
  single_thread: False
  spherical_harmonics: False

  lr:
    cam_rot_delta: 0.003
    cam_trans_delta: 0.001

opt_params:
  iterations: 30000
  position_lr_init: 0.0016
  position_lr_final: 0.0000016
  position_lr_delay_mult: 0.01
  position_lr_max_steps: 30000
  feature_lr: 0.0025
  opacity_lr: 0.05
  scaling_lr: 0.001
  rotation_lr: 0.001
  percent_dense: 0.01
  lambda_dssim: 0.2
  densification_interval: 100
  opacity_reset_interval: 3000
  densify_from_iter: 500
  densify_until_iter: 15000
  densify_grad_threshold: 0.0002

model_params:
  sh_degree: 0
  source_path: ""
  model_path: ""
  resolution: -1
  white_background: False
  data_device: "cuda"

pipeline_params:
  convert_SHs_python: False
  compute_cov3D_python: False
