inherit_from: "thirdparty/MonoGS/configs/mono/rrxio/base_config.yaml"

Dataset:
  modality: 'thermal'

  dataset_path: "datasets/irs_rtvi_datasets_2021/mocap_easy"
  Calibration:
    raw:
      fx: 404.98
      fy: 405.06
      cx: 319.05
      cy: 251.84
      k1: -0.09202092749042277
      k2: 0.04012198239889151
      k3: -0.03795923559427829
      k4: 0.010728597805678742
      width: 640
      height: 512
      depth_scale: 500.0
      distorted: True
      distortion_model: 'equidistant'
    opt:
      # K optimal obtained by cv2.fisheye.estimateNewCameraMatrixForUndistortRectify() with balance=0.0
      fx: 334.19639643
      fy: 334.26241379
      cx: 318.48142004
      cy: 250.56663663
      k1: 0.0
      k2: 0.0
      k3: 0.0
      k4: 0.0
      width: 640
      height: 512
      depth_scale: 500.0
      distorted: False
      distortion_model: ''

